---
# tasks file for role-ssh
- name: ZSH | Ensure git and zsh was installed on Ubuntu
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - sshd

- name: SSH | Setup SSH directory and private key files for root
  include_tasks: configure_ssh.yml
  with_items: "{{ ssh_default_user }}"
  notify: restart sshd
  when:
    - ssh_default_user != "{}"
    - ssh_root_private_key != ''

- name: SSH | Setup SSH directory and private key files for common users
  include_tasks: configure_ssh.yml
  with_items: "{{ ssh_users }}"
  notify: restart sshd
  when:
    - ssh_users != "{}"
