---
# tasks file for role-ssh
- name: SSH | Ensure OpenSSH was installed on {{ ansible_facts['distribution'] }}
  ansible.builtin.package:
    name: openssh-server
    state: present

- include_tasks: configure_ssh.yml
  loop: "{{ ssh_setup_user_root }}"
  loop_control:
    loop_var: ssh_user
  no_log: yes
  when:
    - ssh_setup_user_root != "{}"

- include_tasks: configure_ssh.yml
  loop: "{{ ssh_user_users }}"
  loop_control:
    loop_var: ssh_user
  when: ssh_user_users != "{}"
