---
# tasks file for role-ssh
- name: SSH | Set SSH private key
  set_fact:
    string_in_base64: "{{ private__key }}"

- name: SSH | Check SSH directory exists.
  ansible.builtin.stat:
    path: ~/.ssh
  register: ssh_dir

- name: SSH | Create ssh directory.
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: "0700"
  when: not ssh_dir.stat.exists

- name: SSH | Check id_rsa file
  ansible.builtin.stat:
    path: ~/.ssh/id_rsa
  register: id_rsa_file

- name: SSH | Create a id_rsa file
  ansible.builtin.file:
    path: ~/.ssh/id_rsa
    state: touch
    owner: root
    group: root
    mode: "0600"
  when: not id_rsa_file.stat.exists

- name: SSH | Copy private key
  ansible.builtin.copy:
    content: "{{ string_in_base64 | b64decode }}"
    dest: ~/.ssh/id_rsa
    owner: root
    group: root
    mode: "0600"
  when: id_rsa_file.stat.exists and (string_in_base64 != '')
  notify: restart sshd
