---
- name: Include variables of {{ ansible_os_family | capitalize }}
  ansible.builtin.include_vars:
    file: "{{ item }}.yml"
  loop:
    - "{{ ansible_os_family | lower }}"
    - main

- name: Ensure SSH and dependencies are installed
  ansible.builtin.include_tasks: install.yml

- name: Setup secure SSH config
  ansible.builtin.include_tasks: secure-ssh.yml
  when:
    - ssh_secure_config is defined
    - ssh_secure_config | bool

- name: Configure SSH for root
  ansible.builtin.include_tasks: configure-ssh.yml
  loop: "{{ ssh_setup_user_root }}"
  loop_control:
    loop_var: ssh_user
  # no_log: true
  when:
    - ssh_setup_user_root is defined
    - ssh_setup_user_root | length > 0

- name: Configure SSH for users
  ansible.builtin.include_tasks: configure-ssh.yml
  loop: "{{ ssh_user_users }}"
  loop_control:
    loop_var: ssh_user
  # no_log: true
  when:
    - ssh_user_users is defined
    - ssh_user_users | length > 0
