---
- name: Ensure SSH config file exists
  ansible.builtin.stat:
    path: "{{ ssh_config_file_path }}"
  register: ssh_config_file

- name: Ensure SSH config backup file exists
  ansible.builtin.stat:
    path: "{{ ssh_config_file_path }}.backup"
  register: ssh_config_backup_file

- name: Backup SSH config file
  ansible.builtin.copy:
    src: "{{ ssh_config_file_path }}"
    dest: "{{ ssh_config_file_path }}.backup"
    remote_src: yes
    mode: preserve
  when:
    - ssh_config_file.stat.exists
    - not ssh_config_backup_file.stat.exists

- name: Harden SSH configuration
  become: true
  when: ssh_config_file.stat.exists
  block:

    - name: Deploy custom banner (if defined)
      ansible.builtin.template:
        src: ssh_banner.j2
        dest: "{{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
        owner: root
        group: root
        mode: "0644"
      when:
        - ssh_custom_banner_org_text is defined
        - ssh_custom_banner_org_text | length > 0

    - name: Set Banner path
      ansible.builtin.lineinfile:
        dest: "{{ ssh_config_file_path }}"
        regexp: '^#?\s*Banner\b'
        line: "Banner {{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
        state: present
        mode: "0600"
      when:
        - ssh_custom_banner_org_text is defined
        - ssh_custom_banner_org_text | length > 0

    - name: Update core SSH parameters
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        # validate: "{{ ssh_validate_command | default('sshd -t -f %s') }}"
        mode: "0600"
      loop:
        - { regexp: '^#?\s*Protocol\b',                        line: "Protocol 2" }
        - { regexp: '^#?\s*PasswordAuthentication\b',          line: "PasswordAuthentication {{ ssh_password_authentication }}" }
        - { regexp: '^#?\s*PermitRootLogin\b',                 line: "PermitRootLogin {{ ssh_permit_root_login }}" }
        - { regexp: '^#?\s*Port\b',                            line: "Port {{ ssh_port }}" }
        - { regexp: '^#?\s*MaxAuthTries\b',                    line: "MaxAuthTries {{ ssh_max_auth_tries }}" }
        - { regexp: '^#?\s*LoginGraceTime\b',                  line: "LoginGraceTime {{ ssh_login_grace_time }}" }
        - { regexp: '^#?\s*UseDNS\b',                          line: "UseDNS {{ ssh_usedns }}" }
        - { regexp: '^#?\s*PermitEmptyPasswords\b',            line: "PermitEmptyPasswords {{ ssh_permit_empty_password }}" }
        - { regexp: '^#?\s*ChallengeResponseAuthentication\b', line: "ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}" }
        - { regexp: '^#?\s*GSSAPIAuthentication\b',            line: "GSSAPIAuthentication {{ ssh_gss_api_authentication }}" }
        - { regexp: '^#?\s*X11Forwarding\b',                   line: "X11Forwarding {{ ssh_x11_forwarding }}" }
        - { regexp: '^#?\s*AllowAgentForwarding\b',            line: "AllowAgentForwarding {{ ssh_allow_agent_forwarding }}" }
        - { regexp: '^#?\s*AllowTcpForwarding\b',              line: "AllowTcpForwarding {{ ssh_allow_tcp_forwarding }}" }
        - { regexp: '^#?\s*PermitTunnel\b',                    line: "PermitTunnel {{ ssh_permit_tunnel }}" }
        - { regexp: '^#?\s*PermitUserEnvironment\b',           line: "PermitUserEnvironment {{ ssh_permit_user_env }}" }
        - { regexp: '^#?\s*ClientAliveInterval\b',             line: "ClientAliveInterval {{ ssh_client_alive_interval }}" }
        - { regexp: '^#?\s*ClientAliveCountMax\b',             line: "ClientAliveCountMax {{ ssh_client_alive_count_max }}" }

    - name: Configure allowed users
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: '^#?\s*AllowUsers\b'
        line: "AllowUsers {{ ssh_allow_users | join(' ') }}"
        state: present
        # validate: "{{ ssh_validate_command | default('sshd -t -f %s') }}"
        mode: "0600"
      when:
        - ssh_allow_users is defined
        - ssh_allow_users | length > 0

    - name: Configure allowed groups
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: '^#?\s*AllowGroups\b'
        line: "AllowGroups {{ ssh_allow_group_users | join(' ') }}"
        state: present
        # validate: "{{ ssh_validate_command | default('sshd -t -f %s') }}"
        mode: "0600"
      when:
        - ssh_allow_group_users is defined
        - ssh_allow_group_users | length > 0

    - name: Reload SSH service
      ansible.builtin.debug:
        msg: "Reload ssh service"
      notify: (Handler) Restart SSH
