---
- name: SSH | Allow users to use SSH
  when: ssh_permit_root_login == "no"
  ansible.builtin.assert:
    that: "{{ ssh_allow_users | length > 0 }}"
    fail_msg: "No users defined to allow SSH access"

- name: SSH | Ensure SSH config file exists
  ansible.builtin.stat:
    path: "{{ ssh_config_path }}"
  register: ssh_config_file

- name: SSH | Backup SSH config file
  ansible.builtin.copy:
    src: "{{ ssh_config_path }}"
    dest: "{{ ssh_config_path }}.backup"
    owner: root
    group: root
    mode: '0644'
  when: ssh_config_file.stat.exists

- name: SSH | Update SSH configuration to be more secure
  become: true
  when: ssh_config_file.stat.exists
  block:
    - name: SSH | Custom banner {{ ssh_custom_banner_text }}
      ansible.builtin.shell:
        cmd: figlet "{{ ssh_custom_banner_text }}" >> "{{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
      args:
        chdir: "{{ ssh_custom_banner_path }}/"
        creates: "{{ ssh_custom_banner_file_name }}"
        executable: /bin/bash
      when: ssh_custom_banner_enabled | bool

    - name: SSH | Update SSH configuration to be more secure.
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "sshd -T -f %s"
        mode: '0644'
      with_items:
        - regexp: "^Protocol"
          line: "Protocol 2"
        - regexp: "^PasswordAuthentication"
          line: "PasswordAuthentication {{ ssh_password_authentication }}"
        - regexp: "^PermitRootLogin"
          line: "PermitRootLogin {{ ssh_permit_root_login }}"
        - regexp: "^Port"
          line: "Port {{ ssh_port }}"
        - regexp: "^MaxAuthTries"
          line: "MaxAuthTries {{ ssh_max_auth_tries }}"
        - regexp: "^LoginGraceTime"
          line: "LoginGraceTime {{ ssh_login_grace_time }}"
        - regexp: "^UseDNS"
          line: "UseDNS {{ ssh_usedns }}"
        - regexp: "^PermitEmptyPasswords"
          line: "PermitEmptyPasswords {{ ssh_permit_empty_password }}"
        - regexp: "^ChallengeResponseAuthentication"
          line: "ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}"
        - regexp: "^GSSAPIAuthentication"
          line: "GSSAPIAuthentication {{ ssh_gss_api_authentication }}"
        - regexp: "^X11Forwarding"
          line: "X11Forwarding {{ ssh_x11_forwarding }}"
        - regexp: "^AllowTcpForwarding"
          line: "AllowTcpForwarding {{ ssh_allow_tcp_forwarding }}"
        - regexp: "^AllowAgentForwarding"
          line: "AllowAgentForwarding {{ ssh_allow_agent_forwarding }}"
        - regexp: "^PermitUserEnvironment"
          line: "PermitUserEnvironment {{ ssh_permit_user_env }}"
        - regexp: "^ClientAliveInterval"
          line: "ClientAliveInterval {{ ssh_client_alive_interval }}"
        - regexp: "^ClientAliveCountMax"
          line: "ClientAliveCountMax {{ ssh_client_alive_count_max }}"

    - name: SSH | Update SSH config allow users
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_path }}"
        line: "AllowUsers {{ ssh_allow_users | join(' ') }}"
        state: present
        validate: "sshd -T -f %s"
        mode: '0644'
      when: ssh_permit_root_login == "no"

    - name: SSH | Update SSH config banner
      ansible.builtin.lineinfile:
        dest: "{{ ssh_config_path }}"
        regexp: "^Banner"
        line: "Banner {{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
        state: present
        validate: "sshd -T -f %s"
        mode: '0644'
      when: ssh_custom_banner_enabled | bool

    - name: Reload SSH service
      ansible.builtin.debug:
        msg: "Reload ssh service"
      notify: (Handler) Restart SSH
