---
- name: SSH | Ensure SSH config file exists
  ansible.builtin.stat:
    path: "{{ ssh_config_file_path }}"
  register: ssh_config_file

- name: SSH | Ensure SSH config backup file exists
  ansible.builtin.stat:
    path: "{{ ssh_config_file_path }}.backup"
  register: ssh_config_backup_file

- name: SSH | Backup SSH config file
  ansible.builtin.copy:
    src: "{{ ssh_config_file_path }}"
    dest: "{{ ssh_config_file_path }}.backup"
    remote_src: yes
    mode: preserve
  when:
    - ssh_config_file.stat.exists
    - not ssh_config_backup_file.stat.exists

- name: SSH | Update SSH configuration to be more secure
  become: true
  when: ssh_config_file.stat.exists
  block:
    - name: SSH | Custom banner
      ansible.builtin.template:
        src: ssh_banner.j2
        dest: "{{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
        owner: root
        group: root
        mode: "0644"
      when:
        - ssh_config_file.stat.exists
        - ssh_custom_banner_org_text is defined
        - ssh_custom_banner_org_text | length > 0

    - name: SSH | Update SSH config banner
      ansible.builtin.lineinfile:
        dest: "{{ ssh_config_file_path }}"
        regexp: "^#?Banner"
        line: "Banner {{ ssh_custom_banner_path }}/{{ ssh_custom_banner_file_name }}"
        state: present
        # validate: "{{ ssh_validate_command }}"
        mode: "0600"
      when:
        - ssh_config_file.stat.exists

    - name: SSH | Update SSH configuration to be more secure.
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        validate: "{{ ssh_validate_command }}"
        mode: "0600"
      when: ssh_config_file.stat.exists
      with_items:
        - regexp: "^#?Protocol"
          line: "Protocol 2"
        - regexp: "^#?PasswordAuthentication"
          line: "PasswordAuthentication {{ ssh_password_authentication }}"
        - regexp: "^#?PermitRootLogin"
          line: "PermitRootLogin {{ ssh_permit_root_login }}"
        - regexp: "^#?Port"
          line: "Port {{ ssh_port }}"
        - regexp: "^#?MaxAuthTries"
          line: "MaxAuthTries {{ ssh_max_auth_tries }}"
        - regexp: "^#?LoginGraceTime"
          line: "LoginGraceTime {{ ssh_login_grace_time }}"
        - regexp: "^#?UseDNS"
          line: "UseDNS {{ ssh_usedns }}"
        - regexp: "^#?PermitEmptyPasswords"
          line: "PermitEmptyPasswords {{ ssh_permit_empty_password }}"
        - regexp: "^#?ChallengeResponseAuthentication"
          line: "ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}"
        - regexp: "^#?GSSAPIAuthentication"
          line: "GSSAPIAuthentication {{ ssh_gss_api_authentication }}"
        - regexp: "^#?X11Forwarding"
          line: "X11Forwarding {{ ssh_x11_forwarding }}"
        - regexp: "^#?AllowAgentForwarding"
          line: "AllowAgentForwarding {{ ssh_allow_agent_forwarding }}"
        - regexp: "^#?AllowTcpForwarding"
          line: "AllowTcpForwarding {{ ssh_allow_tcp_forwarding }}"
        - regexp: "^#?PermitTunnel"
          line: "PermitTunnel {{ ssh_permit_tunnel }}"
        - regexp: "^#?PermitUserEnvironment"
          line: "PermitUserEnvironment {{ ssh_permit_user_env }}"
        - regexp: "^#?ClientAliveInterval"
          line: "ClientAliveInterval {{ ssh_client_alive_interval }}"
        - regexp: "^#?ClientAliveCountMax"
          line: "ClientAliveCountMax {{ ssh_client_alive_count_max }}"

    - name: SSH | Update SSH config allow users
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: "^#?AllowUsers"
        line: "AllowUsers {{ ssh_allow_users | join(' ') }}"
        state: present
        validate: "{{ ssh_validate_command }}"
        mode: "0600"
      when:
        - ssh_config_file.stat.exists
        - ssh_allow_users is defined
        - ssh_allow_users | length > 0

    - name: SSH | Update SSH config allow group users
      ansible.builtin.lineinfile:
        path: "{{ ssh_config_file_path }}"
        regexp: "^#?AllowGroups"
        line: "AllowGroups {{ ssh_allow_group_users | join(' ') }}"
        state: present
        validate: "{{ ssh_validate_command }}"
        mode: "0600"
      when:
        - ssh_config_file.stat.exists
        - ssh_allow_group_users is defined
        - ssh_allow_group_users | length > 0

    - name: Reload SSH service
      ansible.builtin.debug:
        msg: "Reload ssh service"
      notify: (Handler) Restart SSH
